config/routes.rb
Ovsm::Application.routes.draw do

  use_link_thumbnailer

	#For now use a custom login controller switch back to devise latter
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions" }
	devise_scope :user do
		root to: "devise/registrations#new"
	end
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :businesses
	get "/feeds/business_root" => "feeds#business_root", as: :business_root
  ActiveAdmin.routes(self)

	resources :users

	get "/feeds" => "feeds#index", as: :user_root
	post "/feeds/fly_and_show" => "feeds#fly_and_show", as: :fly_and_show
  resources :feeds do
		resources :feed_videos, only: [:show]
	end

	resources :posts
	resources :square_photos
	resources :audio_files
	resources :video_files
	match "/panda/authorize_upload", :to => "panda#authorize_upload"
	match "/panda/authorize_upload_audio", :to => "panda#authorize_upload_audio"
	match "/panda/notifications", to: "panda#notifications"

	get "/suitcases/:id/add_post/:post_id" => "suitcases#add_post"
	get "/suitcases/:id/remove_post/:post_id" => "suitcases#remove_post"
	get "/suitcases/post_ids_for_current_user" => "suitcases#post_ids_for_current_user"
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :lat, :lng, :name, :slug, :time_zone
	attr_accessor :distance

	acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng


	has_many :feed_banners
	has_many :feed_videos
	has_many :users
	has_many :businesses
	before_save :update_slug
	before_create :initilize_dependancies, :update_time_zone
	has_one :forecast
	has_many :posts

	def initilize_dependancies
		self.build_forecast
	end

	def update_time_zone
		timezone = Timezone::Zone.new :latlon => [lat, lng]
		self.time_zone = timezone.zone
	end

	def to_param
		slug
	end

	def update_slug
		self.slug = name.parameterize
	end	

	def banner( thumb = false )
		image = feed_banners.where( active: true ).first.image
		thumb ? image.thumb : image
	end

	def current_time
		Time.current.in_time_zone time_zone
	end

	def current_time_stamp
		Time.strptime(current_time.strftime("%I:%M:%S"),"%I:%M:%S").to_i
	end

	def has_video?
		feed_videos.count > 0
	end

	def number_of_users
		users.count
	end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	before_filter :require_login

	def index
		respond_to do |format|
			format.html { render layout: "full_content_span" }
			format.json do
				@feeds = Feed.all
				render json: @feeds
			end
		end
	end

	def business_root
		redirect_to current_business.feed if current_business
		redirect_to new_business_session_path unless current_business
	end

	def fly_and_show
		@feed = Feed.find_by_name( params[:feed][:name] )
		redirect_to @feed
	end

	def show
		@feed = Feed.find_by_slug( params[:id] )
		@forecast = @feed.forecast
		@post_categories = PostCategory.all
	end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.haml
#map
#feed_search
	= simple_form_for Feed.new, url: fly_and_show_path do |f|
		= f.input :name, label: false, autocomplete: "/feeds.json"
		= f.submit "", class: "invisible-plane"

app/views/feeds/show.html.haml
.span-24.feed_show_header
	.banner
		= image_tag @feed.feed_banners.where( active: true ).first.image, class: "feed_banner"
		%h1.name.bullpen= @feed.name
	.weather_widget
		.left_col
			.section.tall
				- today = @forecast.today
				.name= today[:name]
				-# .icon= image_tag today[:icon]
				.icon= icon_to_image( today[:icon], "blue" )
				.high= "#{today[:high]}&deg;".html_safe
				.low= "#{today[:low]}&deg;".html_safe
				.digital_clock
			.section
				.users= "Users: #{@feed.number_of_users}"
			.section.push_down
				- if @feed.has_video?
					= link_to_modal feed_feed_video_path( @feed, 1 ) do
						.video_button
							.video= image_tag "video.png"
							.video_text City Vid
			
		.right_col
			%table
				- @forecast.each_day do |day_name,values|
					%tr
						%td.day_name
							= day_name.upcase[0..2]
						-# %td
							-# = image_tag( "#{values["icon"]}.jpg" )
						%td.icon
							= icon_to_image values["icon"]
						%td.high.temp
							= "#{values["high"]}&deg;".html_safe
						%td.low.temp
							= "#{values["low"]}&deg;".html_safe
.span-24.feed_show_nav
	.top_level
		.tl_select.people.active People
		.tl_select.businesses Businesses
	.categories.people
		.devider
		.link.active.post_type{ data: {type: "all"} }
			.label All
			.image= image_tag "icon-all.png"
		.link.post_type{ data: {type: "text"} }
			.label Text
			.image= image_tag "icon-text.png"
		.link.post_type{ data: {type: "photos"} }
			.label Photos
			.image= image_tag "icon-photo.png"
		.link.post_type{ data: {type: "audio"} }
			.label Audio
			.image= image_tag "icon-audio.png"
		.link.post_type{ data: {type: "links"} }
			.label Links
			.image= image_tag "icon-link.png"
		.link.post_type{ data: {type: "video"} }
			.label Videos
			.image= image_tag "icon-movie.png"
		= select_tag( :post_categories_select, options_for_select( ['All Categories'] + ovsm_optionify( @post_categories ) ) )
	.categories.businesses( style="display:none" )
		.devider
		.link.active.post_type{ data: {type: "all"} }
			.label All
			.image= image_tag "icon-all.png"
		.link.post_type{ data: {type: "deal"} }
			.label Deals
			.image= image_tag "icon-deal.png"
		.link.post_type{ data: {type: "partner"} }
			.label Partners
			.image= image_tag "icon-partner.png"
		.link.post_type{ data: {type: "job"} }
			.label Jobs
			.image= image_tag "icon-job.png"
		.link.post_type{ data: {type: "event"} }
			.label Events
			.image= image_tag "icon-event.png"
		.link.post_type{ data: {type: "product"} }
			.label Products
			.image= image_tag "icon-good.png"

.span-24
	.ovsm_feed_engine(data-bind="template: { name: 'postTemplate', foreach: posts, as: 'post' }")

%time_data{ data: { time: @feed.current_time_stamp * 1000 }}
%post_handle{ data: { handle: @feed.name } }
%feed_data{ data: { id: @feed.id } }
= render "templates/posts.html.erb"